---
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  allowlist_external_dirs:
    - /config
  packages: !include_dir_named packages

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include_dir_merge_list templates
sensor: !include_dir_merge_list sensors

powercalc:

prometheus:

logger:
  default: warning
  # TODO: move to include file
  filters: !include_dir_merge_named log_filters

#   logs:
#     homeassistant.components.mammotion: debug
#     custom_components.mammotion: debug
#     pymammotion: debug
