---
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  allowlist_external_dirs:
    - /config
  packages: !include_dir_named packages

recorder:
  purge_keep_days: 10
  auto_purge: true
  auto_repack: true

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
http: !include http.yaml
template: !include_dir_merge_list templates
sensor: !include_dir_merge_list sensors
# modbus: !include_dir_merge_list modbus

powercalc:

prometheus:

logger:
  default: warning
  # TODO: move to include file
  filters: !include_dir_merge_named log_filters

#   logs:
#     homeassistant.components.mammotion: debug
#     custom_components.mammotion: debug
#     pymammotion: debug

# Notifications
notify:
  - name: "all_devices"
    platform: group
    services:
      - action: mobile_app_iphone
      - action: mobile_app_anns_ipad_air_5

